// <auto-generated />
namespace DashBoard.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtoApplicantNameFound : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtoApplicantNameFound));
        
        string IMigrationMetadata.Id
        {
            get { return "201711102233598_add to Applicant - NameFound"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
